/* 
 * Copyright (c) 2021 Jun-Ki, Hong
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 * 
 * - This file was automatically generated by CMake.
 * - File creation date : 2021-01-24
 */
#ifndef AUTO_CONFIG_DSRW_H_
#define AUTO_CONFIG_DSRW_H_

#ifndef TEST_SYMBOL1
#define TEST_SYMBOL1
#endif /* !TEST_SYMBOL1 */

#ifndef TEST_SYMBOL2
#define TEST_SYMBOL2
#endif /* !TEST_SYMBOL2 */

#ifndef TEST_SYMBOL3
#define TEST_SYMBOL3
#endif /* !TEST_SYMBOL3 */

#ifndef TEST_SYMBOL4
#define TEST_SYMBOL4
#endif /* !TEST_SYMBOL4 */

#ifndef TEST_
#define TEST_ 234
#endif /* !TEST_ */

#endif /* !AUTO_CONFIG_DSRW_H_ */

